services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    # deploy:
    #   replicas: 3
    #   restart_policy:
    #     condition: on-failure
    #     delay: 5s
    #     max_attempts: 3
    env_file: .env
    ports:
      # - "3000-3002:3000"
      - "3000:3000"
    networks:
      - web-network
    environment:
      - NODE_ENV=production
      - PORT=3000
    # healthcheck:
    #   test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3000"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - web-network
    depends_on:
      - nuxt

networks:
  web-network:
    driver: bridge
