services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file: .env
    ports:
      # - "3000-3002:3000"
      - "3000:3000"
    networks:
      - web-network
    environment:
      - NODE_ENV=production
      - PORT=3000
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - web-network
    depends_on:
      - nuxt

networks:
  web-network:
    driver: bridge
